INSERT INTO TIPO_RECEITA ( ID, DESCRICAO) VALUES (1, 'MASSAS');
INSERT INTO TIPO_RECEITA ( ID, DESCRICAO) VALUES (2, 'TIPICAS');
INSERT INTO TIPO_RECEITA ( ID, DESCRICAO) VALUES (3, 'ARABE');
INSERT INTO TIPO_RECEITA ( ID, DESCRICAO) VALUES (4, 'BOLOS');